### ISSUE TITLE
Add to TRANSLATION.md

### ISSUE THREAD

**Issue by oleksii-polovyi** [reactjs/uk.react.dev#210]
> projects - “проєктів” за новим правописом, чи за старим “проектів” ?
> 
> code of conduct - норми поведінки
> 
> contributor covenant - пакт учасників проєкту (дякую гугл)
> 
> pull requests - запит на отримання
> 
> new features - нові функції
> 
> migrate code - мігрування коду
> 
> master branch - основна гілка
> 
> fork - вилка чи лиши форк
> 
> linter - підсвічувач чи лишити лінтер?
> 
> code lints -  код підсвічується
> 
> breaking changes - невід'ємні зміни
> 
> file an issue - подати проблему
> 
> feature flags - прапори особливостей
> open source - оупенсорс чи лишати анг літерами?
> 
> run - виконувати
> 
> debugger - налагоджувач
> 
> folder - директорія
> 
> how to contribute - як зробити внесок
> 
> contribute - внесок
> 
> test case - тестовий випадок
> 
> patch -  пач 
> 
> fetch - ? навіть не знаю
> 
> build - збудувати, будувати
> 
> bounty program - програма винагороди

**Comment by ApolllonDev** [comment]
@lytvyn139 @vldmrkl

**Comment by lytvyn139** [comment]
**моя пропозиція:**
projects - проєктів
code of conduct - норми поведінки
contributor covenant - угода учасників проєкту
pull requests - запит на внесення
new features - нові функції
migrate code - мігрування коду
master branch - основна гілка
fork - вилка
breaking changes - невід'ємні зміни
file an issue - подати проблему
feature flags - прапори особливостей
open source - open source так і лишити, це вже загальний термін як і www
run - виконувати
folder - директорія
how to contribute - як зробити внесок
contribute - внесок
test case - тестовий випадок
patch - пач
build - збудувати
bounty program - програма винагород
debugger - налагоджувач
**дальше не ясно:**
якшо debugger - налагоджувач, то debugging - налагоджування коду
за тою логікою ж 
linter - підсвічувач
code lints - код підсвічується
to fetch - ? от це не знаю
я переклав так 
to fetch its dependencies - додати всі залежності 

ПС: але якшо ми вводимо нові міри то треба буде поміняти слова в всьому проЄкті ? о_О

**Comment by vldmrkl** [comment]
Почнемо з того, що translation.md файл був створений для наших котриб'юторів-перекладачів, як довідка. Я не бачу сенсу вносити до цьєї довідки загальні слова, які не є React- або JS-специфічними (напр. projects). Також, я не думаю, що треба вносити слова, які зустрічаються рідко в документаціії (напр. bounty program).

**Comment by vldmrkl** [comment]
Тепер щодо перекладу projects.

Оскільки ми вже перевели більшу частину документації, використовуючи старий правопис, то для послідовності треба завершити увесь проект з цим правописом. Далі вже можна буде обговорити перехід на новий перепис. 

Також слід зауважити, що це не тільки одне слово (проект -> проєкт) доведеться поміняти на новий правопис, а й усю документацію.

**Comment by vldmrkl** [comment]
@ApolllonDev, @lytvyn139 дайте знати, що ви думаєте з приводу моїх коментарів 👆

**Comment by lytvyn139** [comment]
@vldmrkl я про це також думав, на переправі коней не міняють, нехай тоді все залишається як і було

**Comment by vldmrkl** [comment]
відкрив #211 для обговорення переходу на новий правопис.

**Comment by oleksii-polovyi** [comment]
> #211 

Можна використати [Search and Replace](https://code.visualstudio.com/docs/editor/codebasics#_search-and-replace) щоб швидко замінити на новий правопис.

**Comment by oleksii-polovyi** [comment]
> Я не бачу сенсу вносити до цьєї довідки загальні слова, які не є React- або JS-специфічними (напр. projects).

@lytvyn139 please create a new pull request with the reference to this issue ([About issue references](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references)) for React/JS translations only.
Thank you!
