### ISSUE TITLE
Орфографія: відмінювання нестандартних слів (реф, проп тощо)

### ISSUE THREAD

**Issue by alinkedd** [reactjs/uk.react.dev#506]
Необхідно додати таблиці відмінювання нестандартних (тих, що немає в словниках) слів в однині і множині, щоб узгодити вживання у тексті. Це є `реф`, `рендер`, `проп`, `бандлер` та інші.

Зазвичай проблема полягає у тому, що це слова 2-ої відміни чоловічого роду твердої і мішаної груп, і для них часто є важким підібрати родовий відмінок однини (-a/-я чи -у/-ю). Щонайменше треба хоча б вказати це закінчення в таблиці TRANSLATION.

**Comment by bkatsevych** [comment]
#508
